@MenuAPI_HostAddress = https://localhost:7118


GET {{MenuAPI_HostAddress}}/api/menu/allMenus

###

GET {{MenuAPI_HostAddress}}/api/menu/allMenus

###

GET {{MenuAPI_HostAddress}}/api/menu/allMenus

###

@id=1
DELETE {{MenuAPI_HostAddress}}/api/menu/{{id}}

###

GET {{MenuAPI_HostAddress}}/api/menu/allMenus

###

GET {{MenuAPI_HostAddress}}/api/menu/allMenus

###
